import "./globals.css";
import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import { createClient } from "@/utils/supabase/server";
import { UIProvider } from "./providers/UIProvider";
import { UserProvider } from "./providers/UserProvider";

export const metadata: Metadata = {
  title: "BeatBook",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  let theme;

  if (user) {
    const { data: themeData, error: themeError } = await supabase
      .from("profiles")
      .select("theme")
      .eq("id", user.id)
      .single();

    theme = themeData?.theme;
  }

  return (
    <html lang="ru">
      <body
        className={`${inter.variable} antialiased`}
        data-font="md"
        data-theme={theme}
      >
        <UIProvider>
          <UserProvider user={user}>{children}</UserProvider>
        </UIProvider>
      </body>
    </html>
  );
}
