import "./globals.css";
import type { Metadata } from "next";
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "BeatBook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${inter.variable} antialiased`}
        data-font="md"
        data-theme="dark"
      >
        {children}
      </body>
    </html>
  );
}
